// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ContenteditableJs = require("./contenteditable.js").default;

var make = ContenteditableJs;

exports.make = make;
/* make Not a pure module */
