// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");

function SExpViewer(Props) {
  var data = Props.data;
  var renderList = function (list) {
    return React.createElement("span", {
                className: "list"
              }, $$Array.of_list(List.mapi((function (i, item) {
                          var clazz;
                          clazz = item.TAG === /* Atom */0 || item._0 ? "item" : "item item-nil";
                          return React.createElement("div", {
                                      key: String(i),
                                      className: clazz
                                    }, renderSExp(item));
                        }), list)));
  };
  var renderSExp = function (value) {
    var special;
    var content;
    if (value.TAG === /* Atom */0) {
      var value$1 = value._0;
      return React.createElement("span", {
                  className: "atom"
                }, value$1);
    }
    var list = value._0;
    if (!list) {
      return React.createElement("span", {
                  className: "nil"
                });
    }
    var special$1 = list.hd;
    if (special$1.TAG !== /* Atom */0) {
      return renderList(list);
    }
    var special$2 = special$1._0;
    switch (special$2) {
      case "quote" :
          var match = list.tl;
          if (!match) {
            return renderList(list);
          }
          if (match.tl) {
            return renderList(list);
          }
          special = special$2;
          content = match.hd;
          break;
      case "string" :
          var match$1 = list.tl;
          if (!match$1) {
            return renderList(list);
          }
          var content$1 = match$1.hd;
          if (content$1.TAG === /* Atom */0) {
            return renderList(list);
          }
          if (match$1.tl) {
            return renderList(list);
          }
          special = special$2;
          content = content$1;
          break;
      default:
        return renderList(list);
    }
    return React.createElement("span", {
                className: special
              }, renderSExp(content));
  };
  return renderSExp(data);
}

var make = SExpViewer;

exports.make = make;
/* react Not a pure module */
